services:
  postgres:
    image: postgres:latest
    container_name: postgres-profile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: profile
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-profile
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
