services:
  postgres:
    image: postgres:latest
    container_name: postgres-story
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: story
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-story
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
